name: Build sdist and upload to PyPI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build sdist and upload to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 2

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Build sdist
        run: |
          python -m build --sdist .
          ls -l dist
          tar tvfz dist/batoid_rubin-*.tar.gz

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #       password: ${{ secrets.PYPI_PASSWORD }}
      #       verbose: true
